# Generated by Django 3.0.5 on 2020-04-30 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('street', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(choices=[('Domówka', 'Domówka'), ('Na talerzu', 'Na talerzu'), ('Na ekranie', 'Na ekranie'), ('Na powietrzu', 'Na powietrzu'), ('Obalmy rząd', 'Obalmy rząd')], max_length=16, null=True)),
                ('description', models.TextField(default='Napisz coś o swoim wydarzeniu')),
                ('creatorName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
