# Generated by Django 3.0.5 on 2020-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200430_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='coordinates',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
